src/components/join/Test.js
=> Test: test

src/css/join/_joinmain.scss, src/pages/AuthPage.jsx, src/pages/AuthUserPage.jsx
=> Design: 퍼블리싱중

src/components/layout/RootLayout.jsx, src/css/join/_joinmain.scss, src/css/join/_joinuser.scss, src/pages/AuthCeoPage.jsx, src/pages/AuthPage.jsx, src/pages/AuthUserPage.jsx, src/pages/LoginPage.jsx
- 회원가입 페이지 디자인수정
- 사업자 회원가입 input 요소 타입 지정
=> Design: 회원가입페이지 디자인, 사업자 회원가입 디자인

src/components/restaurantdetail/Menu.js, src/components/restaurantdetail/ModalForMenu.js, src/components/restaurantdetail/info.json, src/components/restaurantdetail/menuItems.json, src/components/restaurantdetail/review.json, src/css/components/_Menu.scss, src/css/components/_ModalForMenu.scss
=> Feats : 각 메뉴 클릭시 개수 정하는 모달 창 추가, 정한 메뉴 주문표에 추가,

src/pages/AuthCeoPage.jsx
=> Design: UI 개선

src/components/join/Mypage.js, src/css/join/_joinmain.scss, src/css/join/_joinuser.scss, src/css/pages/_LogInPage.scss, src/css/pages/_MyPage.scss, src/css/pages/_MypageReviewPage.scss, src/index.scss, src/pages/LoginPage.jsx, src/pages/MyPageReviewPage.jsx
=> Design: 반응형 작업

src/css/join/_joinmain.scss, src/css/join/_joinuser.scss, src/pages/AuthCeoPage.jsx, src/pages/AuthUserPage.jsx
=> Design: UI 디자인 작업

src/components/common/_AddressButton.jsx, src/css/pages/_MyPage.scss, src/pages/MyPageAddress.jsx
=> Feat: 주소입력

src/components/common/MyPageOrderList.jsx, src/components/common/mypage/MypageModal.jsx, src/components/common/mypage/MypageModifyModal.jsx, src/components/common/mypage/MypageReviewWrite.jsx, src/components/join/Mypage.js, src/css/pages/_MyPage.scss, src/css/pages/_MypageReviewPage.scss, src/pages/AuthCeoPage.jsx, src/pages/MyPage.jsx, src/pages/MyPageAddress.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MyPageReviewPage.jsx
- 마이페이지 누락 정보 추가
- 마이페이지 메뉴별 모달 추가
=> Design: 모달 디자인 및 수정

src/App.jsx, src/components/common/mypage/MypageReviewWrite.jsx, src/components/join/Mypage.js, src/css/common/_LocationSearch.scss, src/css/pages/_MyPage.scss, src/pages/AuthUserPage.jsx, src/pages/MyPage.jsx, src/pages/MyPageAddress.jsx, src/pages/MypageUserWithdrawal.jsx
=> Design: 마이페이지 작업

package.json, src/components/common/mypage/MypageModal.jsx, src/components/layout/ImageImport.jsx, src/components/user/mypage/MyMap.jsx, src/css/join/_joinceo.scss, src/css/pages/_MyPage.scss, src/pages/AuthCeoPage.jsx, src/pages/LoginPage.jsx, src/pages/MyPage.jsx, src/pages/MyPageAddress.jsx
=> Feat: 로그인 axios 연동중

.eslintrc.js, package-lock.json, package.json, src/api/user/jwtUtil.js, src/pages/LoginPage.jsx, src/pages/MyPage.jsx, src/utils/cookie.js
=> Feat: 로그인, 마이페이지 데이터 출력 작업

src/components/common/MyPageOrderList.jsx, src/components/common/mypage/MypageReviewWrite.jsx, src/components/user/mypage/PhoneNumberInput.jsx, src/css/pages/_MyPage.scss, src/css/pages/_MypageReviewPage.scss, src/pages/AuthCeoPage.jsx, src/pages/AuthUserPage.jsx, src/pages/LoginPage.jsx, src/pages/MyPage.jsx, src/pages/MyPageAddress.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MyPageReviewPage.jsx
=> Feat: 내주소 기능 수정중

src/components/common/mypage/NotLogin.jsx, src/components/layout/ImageImport.jsx, src/css/join/_joinuser.scss, src/css/pages/_MyPage.scss, src/pages/AuthCeoPage.jsx, src/pages/AuthUserPage.jsx, src/pages/LoginPage.jsx, src/pages/MyPageAddress.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MyPageReviewPage.jsx
=> Feat: 주소부분 수정중

src/components/layout/ImageImport.jsx, src/pages/AuthCeoPage.jsx, src/pages/AuthUserPage.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MypageUserWithdrawal.jsx
=> Feat: 로딩 작업중

src/pages/AuthUserPage.jsx, src/pages/MyPageOrderPagee.jsx
- 회원가입 인증시 alert 2번뜨는 버그 픽스
- 마이페이지 로그인 안되어 있을시 jwtaxios 에러 버그 픽스
=> Fix: 회원가입, 마이페이지 버그 픽스

src/components/common/mypage/MypageReviewWrite.jsx, src/css/pages/_MyPage.scss, src/pages/MyPageAddress.jsx, src/pages/MyPageReviewPage.jsx
=> Fix: 주소페이지 등록, 삭제시 리랜더 작업 완료

src/components/common/mypage/MypageReviewWrite.jsx, src/pages/MyPage.jsx, src/pages/MyPageOrderClosePage.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MyPageReviewPage.jsx
=> Fix: 리뷰쓰기, 리뷰삭제 픽스 완료

src/App.jsx, src/components/user/mypage/OrderListHeader.jsx, src/pages/MyPage.tsx, src/pages/MyPageAddress.jsx, src/pages/MyPageReportListPage.tsx, src/pages/MyPageReviewPage.jsx, src/pages/MypageReportDetailPage.tsx
- 문의 리스트 기능 적용
- 문의하기 기능 적용 해야됨
=> Feat: 문의하기 기능 작업중

src/api/user/jwtUtil.js, src/pages/LoginPage.tsx, src/pages/MyPageAddress.jsx, src/pages/MyPageOrderPagee.jsx, src/pages/MyPageReportListPage.tsx, src/pages/SnsLoginPage.tsx
=> fix: 소셜로그인 완료
